@modul = moysklad

###
// запрос данных на загрузку ассортимента
// ?isLoadingImages=false загрузка без картинок
GET http://{{hostname}}/api/{{modul}}/loadingProduct/?isLoadingImages=false


###
// запрос на загрузку категорий
GET http://{{hostname}}/api/{{modul}}/loadingcategory/


###
// загрузка товаров из мой склад 
GET {{urlMoysklad}}/entity/product
    ?limit=10&filter=updated>=2023-03-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}


###
// загрузка категорий из мой склад 
GET {{urlMoysklad}}/entity/productfolder
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка ассортимента из мой склад 
GET {{urlMoysklad}}/entity/assortment
    ?limit=10&filter=updated>=2023-05-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка картинок
GET https://online.moysklad.ru/api/remap/1.2/entity/bundle/79c6668e-f9e7-11ed-0a80-0275000259d4/images
Authorization: Bearer {{tokenMS}}
responseType: 'stream'



