###
POST http://{{hostname}}/api/property/
content-type: {{contentType}}

{
    "externalCode": "222",
    "vendorCode": "1250",
    "name": "Прожектор",
    "description": "Жопа",
    "archived": "fasle",
    "categoryId": 1,
    "uomId": 1
}


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/property/


###
// Удаление товара по id в body
DELETE http://{{hostname}}/api/property/
content-type: {{contentType}}

{
    "id": 781
}


###
// обновление товара по id в body + Указание полей которые нужно обновить
PUT http://{{hostname}}/api/property/
content-type: {{contentType}}

{
    "id": 5,
     "description": "Прожектор 20 Вт"
} 
