@modul = category


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/{{modul}}/

###
// поиск товаров по полям наименования и описание
GET http://{{hostname}}/api/{{modul}}?search=това

###
POST http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "name": "Настенные светильники",
      "description": "Все светильники линейного типа",
      "parent_id": 3
}

###
// обновление товара по id в body + Указание полей которые нужно обновить
PUT http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "id": 1,
      "description": "Коневая дириктори",
      "parent_id": "#"
} 


###
// Удаление товара по id в body
DELETE http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
    "id": 7
}
