@modul = moysklad

###
// запрос данных с мой склад 
GET http://{{hostname}}/{{modul}}/?isLoadingImages=true


###
// загрузка товаров из мой склад 
GET {{urlMoysklad}}/entity/product
    ?limit=10&filter=updated>=2023-05-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}


###
// загрузка категорий из мой склад 
GET {{urlMoysklad}}/entity/productfolder
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка ассортимента из мой склад 
GET {{urlMoysklad}}/entity/assortment
    ?limit=10&filter=updated>=2023-05-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка картинок
GET https://online.moysklad.ru/api/remap/1.2/entity/product/8d26776b-97a7-11ed-0a80-02a2000761cb/images
Authorization: Bearer {{tokenMS}}
responseType: 'stream'



