@modul = moysklad

###
// запрос данных с мой склад 
GET http://{{hostname}}/{{modul}}/


###
// загрузка товаров из мой склад 
GET {{urlMoysklad}}/entity/product
    ?limit=10&filter=updated>=2023-05-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}


###
// загрузка категорий из мой склад 
GET {{urlMoysklad}}/entity/productfolder
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка ассортимента из мой склад 
GET {{urlMoysklad}}/entity/assortment
    ?limit=10&filter=updated>=2023-05-24 06:43
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}

###
// загрузка модификаций товаров из мой склад 
GET {{urlMoysklad}}/entity/variant
Authorization: Bearer {{tokenMS}}
Content-Type: {{contentType}}


