@modul = authentication



###
// Плучение токена авторизации
POST http://{{hostname}}/auth/{{modul}}/in/
content-type: {{contentType}}

{
  "phone": "89501266972",
  "position": "Директор",
}


###
// Плучение токена авторизации
GET http://{{hostname}}/auth/{{modul}}/

###
// поиск товаров по полям наименования и описание
GET http://{{hostname}}/auth/{{modul}}/testAuth/
user: sander
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2FuZGVyIiwiaWF0IjoxNjc4NDUyMDc4LCJleHAiOjE2Nzg0NTU2Nzh9.Mjwc12ZFaxLHhyc-mnxfvJbaM3GuQrVZc62DkeDI3Fg


###
// поиск товаров по id
GET http://{{hostname}}/api/{{modul}}?id=6


###
POST http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "fullName": "user 12",
      "name": "name user 12",
      "phone": "89501266972"
}

###
// Удаление товара по id запросе
DELETE http://{{hostname}}/api/{{modul}}?id=7
content-type: {{contentType}}

{
      "id": 2
} 