@modul = employee


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/{{modul}}/

###
// поиск товаров по полям наименования и описание
GET http://{{hostname}}/api/{{modul}}?search=дир


###
// поиск товаров по id
GET http://{{hostname}}/api/{{modul}}?id=6


###
POST http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "fullName": "user 12",
      "name": "name user 12",
      "phone": "89501266972"
}

###
// обновление товара по id в body + Указание полей которые нужно обновить
PUT http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "id": 11,
      "position": "Директор",
      "password": "1234йцы5"
} 


###
// Удаление товара по id запросе
DELETE http://{{hostname}}/api/{{modul}}?id=7
content-type: {{contentType}}

{
      "id": 2
} 