@modul = employee


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/{{modul}}/

###
// поиск товаров по полям наименования и описание
GET http://{{hostname}}/api/{{modul}}?search=


###
// поиск товаров по id
GET http://{{hostname}}/api/{{modul}}?id=9


###
POST http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "fullName": "user 13",
      "name": "name user 13",
      "phone": "89501266974"
}

###
// обновление товара по id в body + Указание полей которые нужно обновить
PUT http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "id": 13,
      "password": "12345",
      "position": "super user"
} 


###
// Удаление товара по id запросе
DELETE http://{{hostname}}/api/{{modul}}?id=7
content-type: {{contentType}}

{
      "id": 2
} 