@modul = marketplace


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/{{modul}}/

###
// поиск товаров по полям наименования и описание
GET http://{{hostname}}/api/{{modul}}?search=ва

###
POST http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
      "name": "OZON"
}

###
// обновление товара по id в body + Указание полей которые нужно обновить
PUT http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
    "id": 2,
    "name": "Вайлбериз",
    "token": "651df65vb1df65v156df1v",
    "description": "Работаем со своего склада"
} 


###
// Удаление товара по id в body
DELETE http://{{hostname}}/api/{{modul}}/
content-type: {{contentType}}

{
    "id": 1
}
