@modul = avito

###
// запрос данных на загрузку ассортимента
// ?isLoadingImages=false загрузка без картинок
GET http://{{hostname}}/api/{{modul}}/createXml/



# Запрос всех параметров для маркетплейса
###
GET http://{{hostname}}/api/{{modul}}/property/



###
// Получение токена на авито
POST  {{urlAvito}}/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{tokenAvito_id}}&client_secret={{tokenAvito_secret}}

###
// запрос списка обьявлений из авито 
GET {{urlAvito}}/core/v1/items
Authorization: Bearer {{tokenAvito}}
Content-Type: application/json


###
// запрос обьявлениz из авито 
GET {{urlAvito}}/core/v1/accounts/231519117/items/2955107206/
Authorization: Bearer {{tokenAvito}}
Content-Type: application/json

