@module = user


###
// вывод всех товаров из таблицы
GET http://{{hostname}}/api/{{module}}/
Authorization: {{token}}


###
POST http://{{hostname}}/api/{{module}}/
content-type: {{contentType}}
{
    "name": "Sander",
    "login": "sander",
    "password": "123456",
    "isAdmin": 1,
    "isSuperAdmin": 1,
}
###
DELETE http://{{hostname}}/api/{{module}}/
content-type: {{contentType}}
{
    "id": 3115
}

###
PUT http://{{hostname}}/api/{{module}}/
content-type: {{contentType}}

{
    "id": 5,
     "description": "Прожектор 20 Вт"
} 
